"""sports-agnostic tables and mlb specific tables

Initial (base) migration. Creates the entire schema from scratch: the
sport-agnostic core tables (venues, teams, players, games, odds, predictions,
bets, weather, stat events, operational logs) and the MLB-specific extension
tables (game details, player profiles, pitch events, arsenals, splits,
standings, park factors, etc.), along with their indexes and the ``sport_enum``
type. Auto-generated by Alembic; ``down_revision`` is ``None`` because this is
the first revision.

Revision ID: 8610aacd7d0f
Revises:
Create Date: 2026-05-17 12:48:06.709616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8610aacd7d0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all tables, indexes, and enum types for the initial schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_sport'), 'ingestion_runs', ['sport'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_window_start', sa.Date(), nullable=False),
    sa.Column('training_window_end', sa.Date(), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=100), nullable=True),
    sa.Column('hyperparams', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_registry_name_version')
    )
    op.create_index(op.f('ix_model_registry_sport'), 'model_registry', ['sport'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('sport', sa.Enum('mlb', 'nba', 'nhl', 'nfl', 'atp', name='sport_enum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=50), nullable=True),
    sa.Column('roof_type', sa.String(length=50), nullable=True),
    sa.Column('elevation_ft', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_venues_sport'), 'venues', ['sport'], unique=False)
    op.create_table('park_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('lf_distance_ft', sa.Integer(), nullable=True),
    sa.Column('cf_distance_ft', sa.Integer(), nullable=True),
    sa.Column('rf_distance_ft', sa.Integer(), nullable=True),
    sa.Column('lf_wall_height_ft', sa.Integer(), nullable=True),
    sa.Column('rf_wall_height_ft', sa.Integer(), nullable=True),
    sa.Column('factor_runs', sa.Float(), nullable=False),
    sa.Column('factor_hr_vs_l', sa.Float(), nullable=False),
    sa.Column('factor_hr_vs_r', sa.Float(), nullable=False),
    sa.Column('factor_hits', sa.Float(), nullable=False),
    sa.Column('factor_singles', sa.Float(), nullable=False),
    sa.Column('factor_doubles', sa.Float(), nullable=False),
    sa.Column('factor_triples', sa.Float(), nullable=False),
    sa.Column('factor_bb', sa.Float(), nullable=False),
    sa.Column('factor_so', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'season', name='uq_park_factors_venue_season')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.Enum('mlb', 'nba', 'nhl', 'nfl', 'atp', name='sport_enum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('conference', sa.String(length=50), nullable=True),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=10), nullable=True),
    sa.Column('secondary_color', sa.String(length=10), nullable=True),
    sa.Column('home_venue_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_sport'), 'teams', ['sport'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp_f', sa.Integer(), nullable=True),
    sa.Column('wind_mph', sa.Integer(), nullable=True),
    sa.Column('wind_dir_deg', sa.Integer(), nullable=True),
    sa.Column('humidity_pct', sa.Integer(), nullable=True),
    sa.Column('precip_chance_pct', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id', 'captured_at')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('sport', sa.Enum('mlb', 'nba', 'nhl', 'nfl', 'atp', name='sport_enum'), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('start_time_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('is_postseason', sa.Boolean(), nullable=False),
    sa.Column('weather_temp_f', sa.Integer(), nullable=True),
    sa.Column('weather_wind_mph', sa.Integer(), nullable=True),
    sa.Column('weather_wind_dir_deg', sa.Integer(), nullable=True),
    sa.Column('weather_wind_dir_text', sa.String(length=20), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('weather_humidity_pct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_games_sport'), 'games', ['sport'], unique=False)
    op.create_table('mlb_standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_pct', sa.Float(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('runs_allowed', sa.Integer(), nullable=False),
    sa.Column('run_diff', sa.Integer(), nullable=False),
    sa.Column('pythag_win_pct', sa.Float(), nullable=False),
    sa.Column('games_back', sa.Float(), nullable=False),
    sa.Column('division_rank', sa.Integer(), nullable=False),
    sa.Column('league_rank', sa.Integer(), nullable=False),
    sa.Column('wildcard_rank', sa.Integer(), nullable=True),
    sa.Column('last_10_wins', sa.Integer(), nullable=False),
    sa.Column('last_10_losses', sa.Integer(), nullable=False),
    sa.Column('streak_type', sa.String(length=1), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'as_of_date', name='uq_mlb_standings_team_date')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.Enum('mlb', 'nba', 'nhl', 'nfl', 'atp', name='sport_enum'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_country', sa.String(length=100), nullable=True),
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('primary_role', sa.String(length=50), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('bats', sa.String(length=50), nullable=True),
    sa.Column('throws', sa.String(length=50), nullable=True),
    sa.Column('debut_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_players_sport'), 'players', ['sport'], unique=False)
    op.create_table('at_bats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('half_inning', sa.String(length=10), nullable=False),
    sa.Column('at_bat_num', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_throws', sa.String(length=1), nullable=True),
    sa.Column('batter_stands', sa.String(length=1), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('pitch_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'at_bat_num', name='uq_at_bats_game_abnum')
    )
    op.create_table('batter_vs_pitcher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('home_runs', sa.Integer(), nullable=False),
    sa.Column('strikeouts', sa.Integer(), nullable=False),
    sa.Column('walks', sa.Integer(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('obp', sa.Float(), nullable=True),
    sa.Column('slg', sa.Float(), nullable=True),
    sa.Column('xwoba', sa.Float(), nullable=True),
    sa.Column('last_faced_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batter_id', 'pitcher_id', name='uq_bvp_batter_pitcher')
    )
    op.create_table('book_odds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('book', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('american_price', sa.Integer(), nullable=False),
    sa.Column('decimal_price', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id', 'captured_at')
    )
    op.create_index('ix_book_odds_game_market_book_captured', 'book_odds', ['game_id', 'market', 'book', 'captured_at'], unique=False)
    op.create_index('ix_book_odds_player_market_captured', 'book_odds', ['player_id', 'market', 'captured_at'], unique=False)
    op.create_index(op.f('ix_book_odds_sport'), 'book_odds', ['sport'], unique=False)
    op.create_table('bullpen_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('pitches_yesterday', sa.Integer(), nullable=False),
    sa.Column('pitches_2days_ago', sa.Integer(), nullable=False),
    sa.Column('pitches_3days_ago', sa.Integer(), nullable=False),
    sa.Column('appearances_last_7d', sa.Integer(), nullable=False),
    sa.Column('is_back_to_back', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_bullpen_avail_game_player')
    )
    op.create_table('closing_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('american_price', sa.Integer(), nullable=False),
    sa.Column('decimal_price', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'book', 'market', 'period', 'side', name='uq_closing_line_game_book_market_period_side')
    )
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'side', 'feature_version', name='uq_feature_snapshot_game_side_version')
    )
    op.create_index(op.f('ix_feature_snapshots_sport'), 'feature_snapshots', ['sport'], unique=False)
    op.create_table('game_lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', 'batting_order', 'is_starter', name='uq_game_lineups_slot')
    )
    op.create_index('ix_game_lineups_game_team', 'game_lineups', ['game_id', 'team_id'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_injuries_player_is_current', 'injuries', ['player_id', 'is_current'], unique=False)
    op.create_table('mlb_game_details',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('mlb_game_pk', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=5), nullable=False),
    sa.Column('home_starter_id', sa.Integer(), nullable=True),
    sa.Column('away_starter_id', sa.Integer(), nullable=True),
    sa.Column('winning_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('losing_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('save_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('total_innings', sa.Integer(), nullable=True),
    sa.Column('home_runs_by_inning', sa.JSON(), nullable=True),
    sa.Column('away_runs_by_inning', sa.JSON(), nullable=True),
    sa.Column('is_doubleheader', sa.Boolean(), nullable=False),
    sa.Column('doubleheader_game_num', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_starter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_starter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['losing_pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['save_pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winning_pitcher_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_mlb_game_details_mlb_game_pk'), 'mlb_game_details', ['mlb_game_pk'], unique=True)
    op.create_table('mlb_player_profiles',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('mlb_player_id', sa.Integer(), nullable=False),
    sa.Column('bbref_id', sa.String(length=50), nullable=True),
    sa.Column('fangraphs_id', sa.String(length=50), nullable=True),
    sa.Column('retrosheet_id', sa.String(length=50), nullable=True),
    sa.Column('mlb_service_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_mlb_player_profiles_bbref_id'), 'mlb_player_profiles', ['bbref_id'], unique=False)
    op.create_index(op.f('ix_mlb_player_profiles_fangraphs_id'), 'mlb_player_profiles', ['fangraphs_id'], unique=False)
    op.create_index(op.f('ix_mlb_player_profiles_mlb_player_id'), 'mlb_player_profiles', ['mlb_player_id'], unique=True)
    op.create_table('mlb_player_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('pa', sa.Integer(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('stolen_bases', sa.Integer(), nullable=True),
    sa.Column('caught_stealing', sa.Integer(), nullable=True),
    sa.Column('hbp', sa.Integer(), nullable=True),
    sa.Column('sac_flies', sa.Integer(), nullable=True),
    sa.Column('sac_hits', sa.Integer(), nullable=True),
    sa.Column('gidp', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('obp', sa.Float(), nullable=True),
    sa.Column('slg', sa.Float(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('iso', sa.Float(), nullable=True),
    sa.Column('babip', sa.Float(), nullable=True),
    sa.Column('k_pct', sa.Float(), nullable=True),
    sa.Column('bb_pct', sa.Float(), nullable=True),
    sa.Column('hr_per_fb', sa.Float(), nullable=True),
    sa.Column('woba', sa.Float(), nullable=True),
    sa.Column('wrc_plus', sa.Float(), nullable=True),
    sa.Column('war', sa.Float(), nullable=True),
    sa.Column('avg_exit_velocity', sa.Float(), nullable=True),
    sa.Column('max_exit_velocity', sa.Float(), nullable=True),
    sa.Column('avg_launch_angle', sa.Float(), nullable=True),
    sa.Column('sweet_spot_pct', sa.Float(), nullable=True),
    sa.Column('hard_hit_pct', sa.Float(), nullable=True),
    sa.Column('barrel_pct', sa.Float(), nullable=True),
    sa.Column('xba', sa.Float(), nullable=True),
    sa.Column('xslg', sa.Float(), nullable=True),
    sa.Column('xwoba', sa.Float(), nullable=True),
    sa.Column('xiso', sa.Float(), nullable=True),
    sa.Column('whiff_pct', sa.Float(), nullable=True),
    sa.Column('chase_pct', sa.Float(), nullable=True),
    sa.Column('zone_contact_pct', sa.Float(), nullable=True),
    sa.Column('sprint_speed_ft_per_sec', sa.Float(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('hits_allowed', sa.Integer(), nullable=True),
    sa.Column('runs_allowed', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('hr_allowed', sa.Integer(), nullable=True),
    sa.Column('qs', sa.Integer(), nullable=True),
    sa.Column('holds', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('blown_saves', sa.Integer(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('fip', sa.Float(), nullable=True),
    sa.Column('xfip', sa.Float(), nullable=True),
    sa.Column('siera', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('k_per_9', sa.Float(), nullable=True),
    sa.Column('bb_per_9', sa.Float(), nullable=True),
    sa.Column('hr_per_9', sa.Float(), nullable=True),
    sa.Column('k_bb_pct', sa.Float(), nullable=True),
    sa.Column('lob_pct', sa.Float(), nullable=True),
    sa.Column('gb_pct', sa.Float(), nullable=True),
    sa.Column('fb_pct', sa.Float(), nullable=True),
    sa.Column('avg_fb_velocity', sa.Float(), nullable=True),
    sa.Column('avg_fb_spin_rate', sa.Float(), nullable=True),
    sa.Column('csw_pct', sa.Float(), nullable=True),
    sa.Column('zone_pct', sa.Float(), nullable=True),
    sa.Column('first_pitch_strike_pct', sa.Float(), nullable=True),
    sa.Column('barrel_pct_allowed', sa.Float(), nullable=True),
    sa.Column('hard_hit_pct_allowed', sa.Float(), nullable=True),
    sa.Column('xera', sa.Float(), nullable=True),
    sa.Column('xwoba_allowed', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'role', name='uq_mlb_season_stats_player_season_role')
    )
    op.create_table('mlb_player_split_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('split_type', sa.String(length=20), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('pa', sa.Integer(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('stolen_bases', sa.Integer(), nullable=True),
    sa.Column('caught_stealing', sa.Integer(), nullable=True),
    sa.Column('hbp', sa.Integer(), nullable=True),
    sa.Column('sac_flies', sa.Integer(), nullable=True),
    sa.Column('sac_hits', sa.Integer(), nullable=True),
    sa.Column('gidp', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('obp', sa.Float(), nullable=True),
    sa.Column('slg', sa.Float(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('iso', sa.Float(), nullable=True),
    sa.Column('babip', sa.Float(), nullable=True),
    sa.Column('k_pct', sa.Float(), nullable=True),
    sa.Column('bb_pct', sa.Float(), nullable=True),
    sa.Column('hr_per_fb', sa.Float(), nullable=True),
    sa.Column('woba', sa.Float(), nullable=True),
    sa.Column('wrc_plus', sa.Float(), nullable=True),
    sa.Column('war', sa.Float(), nullable=True),
    sa.Column('avg_exit_velocity', sa.Float(), nullable=True),
    sa.Column('max_exit_velocity', sa.Float(), nullable=True),
    sa.Column('avg_launch_angle', sa.Float(), nullable=True),
    sa.Column('sweet_spot_pct', sa.Float(), nullable=True),
    sa.Column('hard_hit_pct', sa.Float(), nullable=True),
    sa.Column('barrel_pct', sa.Float(), nullable=True),
    sa.Column('xba', sa.Float(), nullable=True),
    sa.Column('xslg', sa.Float(), nullable=True),
    sa.Column('xwoba', sa.Float(), nullable=True),
    sa.Column('xiso', sa.Float(), nullable=True),
    sa.Column('whiff_pct', sa.Float(), nullable=True),
    sa.Column('chase_pct', sa.Float(), nullable=True),
    sa.Column('zone_contact_pct', sa.Float(), nullable=True),
    sa.Column('sprint_speed_ft_per_sec', sa.Float(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('hits_allowed', sa.Integer(), nullable=True),
    sa.Column('runs_allowed', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('hr_allowed', sa.Integer(), nullable=True),
    sa.Column('qs', sa.Integer(), nullable=True),
    sa.Column('holds', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('blown_saves', sa.Integer(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('fip', sa.Float(), nullable=True),
    sa.Column('xfip', sa.Float(), nullable=True),
    sa.Column('siera', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('k_per_9', sa.Float(), nullable=True),
    sa.Column('bb_per_9', sa.Float(), nullable=True),
    sa.Column('hr_per_9', sa.Float(), nullable=True),
    sa.Column('k_bb_pct', sa.Float(), nullable=True),
    sa.Column('lob_pct', sa.Float(), nullable=True),
    sa.Column('gb_pct', sa.Float(), nullable=True),
    sa.Column('fb_pct', sa.Float(), nullable=True),
    sa.Column('avg_fb_velocity', sa.Float(), nullable=True),
    sa.Column('avg_fb_spin_rate', sa.Float(), nullable=True),
    sa.Column('csw_pct', sa.Float(), nullable=True),
    sa.Column('zone_pct', sa.Float(), nullable=True),
    sa.Column('first_pitch_strike_pct', sa.Float(), nullable=True),
    sa.Column('barrel_pct_allowed', sa.Float(), nullable=True),
    sa.Column('hard_hit_pct_allowed', sa.Float(), nullable=True),
    sa.Column('xera', sa.Float(), nullable=True),
    sa.Column('xwoba_allowed', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'role', 'split_type', name='uq_mlb_split_stats_player_season_role_split')
    )
    op.create_table('pitch_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mlb_play_id', sa.String(length=50), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('half_inning', sa.String(length=10), nullable=False),
    sa.Column('at_bat_num', sa.Integer(), nullable=False),
    sa.Column('pitch_num', sa.Integer(), nullable=False),
    sa.Column('balls', sa.Integer(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('outs_when_up', sa.Integer(), nullable=False),
    sa.Column('pitcher_throws', sa.String(length=1), nullable=True),
    sa.Column('batter_stands', sa.String(length=1), nullable=True),
    sa.Column('pitch_type', sa.String(length=5), nullable=True),
    sa.Column('pitch_name', sa.String(length=50), nullable=True),
    sa.Column('release_speed_mph', sa.Float(), nullable=True),
    sa.Column('effective_speed_mph', sa.Float(), nullable=True),
    sa.Column('release_spin_rate', sa.Integer(), nullable=True),
    sa.Column('release_pos_x', sa.Float(), nullable=True),
    sa.Column('release_pos_y', sa.Float(), nullable=True),
    sa.Column('release_pos_z', sa.Float(), nullable=True),
    sa.Column('pfx_x', sa.Float(), nullable=True),
    sa.Column('pfx_z', sa.Float(), nullable=True),
    sa.Column('plate_x', sa.Float(), nullable=True),
    sa.Column('plate_z', sa.Float(), nullable=True),
    sa.Column('vx0', sa.Float(), nullable=True),
    sa.Column('vy0', sa.Float(), nullable=True),
    sa.Column('vz0', sa.Float(), nullable=True),
    sa.Column('ax', sa.Float(), nullable=True),
    sa.Column('ay', sa.Float(), nullable=True),
    sa.Column('az', sa.Float(), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('events', sa.String(length=100), nullable=True),
    sa.Column('launch_speed_mph', sa.Float(), nullable=True),
    sa.Column('launch_angle_deg', sa.Float(), nullable=True),
    sa.Column('hit_location', sa.Integer(), nullable=True),
    sa.Column('bb_type', sa.String(length=20), nullable=True),
    sa.Column('hit_distance_ft', sa.Integer(), nullable=True),
    sa.Column('estimated_ba', sa.Float(), nullable=True),
    sa.Column('estimated_slg', sa.Float(), nullable=True),
    sa.Column('estimated_woba', sa.Float(), nullable=True),
    sa.Column('woba_value', sa.Float(), nullable=True),
    sa.Column('woba_denom', sa.Integer(), nullable=True),
    sa.Column('babip_value', sa.Float(), nullable=True),
    sa.Column('iso_value', sa.Float(), nullable=True),
    sa.Column('pitch_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id', 'pitch_time')
    )
    op.create_index('ix_pitch_events_batter_time', 'pitch_events', ['batter_id', 'pitch_time'], unique=False)
    op.create_index('ix_pitch_events_game_ab_pitch', 'pitch_events', ['game_id', 'at_bat_num', 'pitch_num'], unique=False)
    op.create_index(op.f('ix_pitch_events_mlb_play_id'), 'pitch_events', ['mlb_play_id'], unique=False)
    op.create_index(op.f('ix_pitch_events_pitch_time'), 'pitch_events', ['pitch_time'], unique=False)
    op.create_index('ix_pitch_events_pitcher_time', 'pitch_events', ['pitcher_id', 'pitch_time'], unique=False)
    op.create_table('pitcher_arsenals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('pitch_type', sa.String(length=5), nullable=False),
    sa.Column('pitch_count', sa.Integer(), nullable=False),
    sa.Column('usage_pct', sa.Float(), nullable=False),
    sa.Column('avg_velocity', sa.Float(), nullable=True),
    sa.Column('avg_spin_rate', sa.Integer(), nullable=True),
    sa.Column('avg_pfx_x', sa.Float(), nullable=True),
    sa.Column('avg_pfx_z', sa.Float(), nullable=True),
    sa.Column('whiff_pct', sa.Float(), nullable=True),
    sa.Column('csw_pct', sa.Float(), nullable=True),
    sa.Column('chase_pct', sa.Float(), nullable=True),
    sa.Column('xwoba_against', sa.Float(), nullable=True),
    sa.Column('slg_against', sa.Float(), nullable=True),
    sa.Column('vs_lhh_woba', sa.Float(), nullable=True),
    sa.Column('vs_rhh_woba', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pitcher_id', 'season', 'pitch_type', name='uq_pitcher_arsenal_pitcher_season_type')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('predicted_prob', sa.Float(), nullable=True),
    sa.Column('predicted_distribution', sa.JSON(), nullable=True),
    sa.Column('book_implied_prob', sa.Float(), nullable=True),
    sa.Column('edge_pct', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('recommended_stake_pct', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id', 'occurred_at')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('book', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('taken_american_price', sa.Integer(), nullable=False),
    sa.Column('stake_units', sa.Float(), nullable=False),
    sa.Column('stake_dollars', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('pnl_units', sa.Float(), nullable=True),
    sa.Column('pnl_dollars', sa.Float(), nullable=True),
    sa.Column('captured_clv_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Convert time-series tables to TimescaleDB hypertables
    op.execute("SELECT create_hypertable('stat_events', 'occurred_at', if_not_exists => TRUE);")
    op.execute("SELECT create_hypertable('pitch_events', 'pitch_time', if_not_exists => TRUE);")
    op.execute("SELECT create_hypertable('book_odds', 'captured_at', if_not_exists => TRUE);")
    op.execute("SELECT create_hypertable('weather_snapshots', 'captured_at', if_not_exists => TRUE);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop all tables, indexes, and enum types, reverting to an empty schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet_records')
    op.drop_table('transactions')
    op.drop_table('stat_events')
    op.drop_table('predictions')
    op.drop_table('pitcher_arsenals')
    op.drop_index('ix_pitch_events_pitcher_time', table_name='pitch_events')
    op.drop_index(op.f('ix_pitch_events_pitch_time'), table_name='pitch_events')
    op.drop_index(op.f('ix_pitch_events_mlb_play_id'), table_name='pitch_events')
    op.drop_index('ix_pitch_events_game_ab_pitch', table_name='pitch_events')
    op.drop_index('ix_pitch_events_batter_time', table_name='pitch_events')
    op.drop_table('pitch_events')
    op.drop_table('mlb_player_split_stats')
    op.drop_table('mlb_player_season_stats')
    op.drop_index(op.f('ix_mlb_player_profiles_mlb_player_id'), table_name='mlb_player_profiles')
    op.drop_index(op.f('ix_mlb_player_profiles_fangraphs_id'), table_name='mlb_player_profiles')
    op.drop_index(op.f('ix_mlb_player_profiles_bbref_id'), table_name='mlb_player_profiles')
    op.drop_table('mlb_player_profiles')
    op.drop_index(op.f('ix_mlb_game_details_mlb_game_pk'), table_name='mlb_game_details')
    op.drop_table('mlb_game_details')
    op.drop_index('ix_injuries_player_is_current', table_name='injuries')
    op.drop_table('injuries')
    op.drop_index('ix_game_lineups_game_team', table_name='game_lineups')
    op.drop_table('game_lineups')
    op.drop_index(op.f('ix_feature_snapshots_sport'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_table('closing_lines')
    op.drop_table('bullpen_availability')
    op.drop_index(op.f('ix_book_odds_sport'), table_name='book_odds')
    op.drop_index('ix_book_odds_player_market_captured', table_name='book_odds')
    op.drop_index('ix_book_odds_game_market_book_captured', table_name='book_odds')
    op.drop_table('book_odds')
    op.drop_table('batter_vs_pitcher')
    op.drop_table('at_bats')
    op.drop_index(op.f('ix_players_sport'), table_name='players')
    op.drop_table('players')
    op.drop_table('mlb_standings')
    op.drop_index(op.f('ix_games_sport'), table_name='games')
    op.drop_table('games')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_teams_sport'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('park_factors')
    op.drop_index(op.f('ix_venues_sport'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_model_registry_sport'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_ingestion_runs_sport'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # Drop Sports Enum type #
    op.execute("DROP TYPE IF EXISTS sport_enum")
    # ### end Alembic commands ###
