"""split park dimensions; rolling window

Revision ID: e5250520d76d
Revises: 8610aacd7d0f
Create Date: 2026-06-08 09:12:26.569042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5250520d76d'
down_revision: Union[str, None] = '8610aacd7d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('park_dimensions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('lf_distance_ft', sa.Float(), nullable=True),
    sa.Column('cf_distance_ft', sa.Float(), nullable=True),
    sa.Column('rf_distance_ft', sa.Float(), nullable=True),
    sa.Column('lf_gap_distance_ft', sa.Float(), nullable=True),
    sa.Column('rf_gap_distance_ft', sa.Float(), nullable=True),
    sa.Column('lf_wall_height_ft', sa.Float(), nullable=True),
    sa.Column('cf_wall_height_ft', sa.Float(), nullable=True),
    sa.Column('rf_wall_height_ft', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'season', name='uq_park_dimensions_venue_season')
    )
    # Clear pre-existing template rows: their source values ('fangraphs' /
    # 'baseballsavant') would violate the new ck_park_factors_source check,
    # and the data is being reseeded from scratch anyway.
    op.execute("DELETE FROM park_factors")
    op.add_column('park_factors', sa.Column('window_years', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('park_factors', sa.Column('factor_overall', sa.Float(), nullable=True))
    op.add_column('park_factors', sa.Column('factor_xwobacon', sa.Float(), nullable=True))
    op.add_column('park_factors', sa.Column('factor_obp', sa.Float(), nullable=True))
    op.add_column('park_factors', sa.Column('factor_hardhit', sa.Float(), nullable=True))
    op.add_column('park_factors', sa.Column('pa', sa.Integer(), nullable=True))
    op.alter_column('park_factors', 'factor_runs',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('park_factors', 'factor_hr_vs_l',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('park_factors', 'factor_hr_vs_r',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('park_factors', 'factor_hits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('park_factors', 'factor_bb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('park_factors', 'factor_so',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('uq_park_factors_venue_season'), 'park_factors', type_='unique')
    op.create_unique_constraint('uq_park_factors_venue_season_window', 'park_factors', ['venue_id', 'season', 'window_years'])
    op.create_check_constraint(
        'ck_park_factors_source', 'park_factors',
        "source IN ('baseball_savant', 'computed')",
    )
    op.drop_column('park_factors', 'rf_wall_height_ft')
    op.drop_column('park_factors', 'cf_distance_ft')
    op.drop_column('park_factors', 'lf_distance_ft')
    op.drop_column('park_factors', 'factor_singles')
    op.drop_column('park_factors', 'factor_doubles')
    op.drop_column('park_factors', 'factor_triples')
    op.drop_column('park_factors', 'rf_distance_ft')
    op.drop_column('park_factors', 'lf_wall_height_ft')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_park_factors_source', 'park_factors', type_='check')
    op.add_column('park_factors', sa.Column('lf_wall_height_ft', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('park_factors', sa.Column('rf_distance_ft', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('park_factors', sa.Column('factor_triples', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('park_factors', sa.Column('factor_doubles', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('park_factors', sa.Column('factor_singles', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('park_factors', sa.Column('lf_distance_ft', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('park_factors', sa.Column('cf_distance_ft', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('park_factors', sa.Column('rf_wall_height_ft', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_park_factors_venue_season_window', 'park_factors', type_='unique')
    op.create_unique_constraint(op.f('uq_park_factors_venue_season'), 'park_factors', ['venue_id', 'season'], postgresql_nulls_not_distinct=False)
    op.alter_column('park_factors', 'factor_so',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('park_factors', 'factor_bb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('park_factors', 'factor_hits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('park_factors', 'factor_hr_vs_r',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('park_factors', 'factor_hr_vs_l',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('park_factors', 'factor_runs',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('park_factors', 'pa')
    op.drop_column('park_factors', 'factor_hardhit')
    op.drop_column('park_factors', 'factor_obp')
    op.drop_column('park_factors', 'factor_xwobacon')
    op.drop_column('park_factors', 'factor_overall')
    op.drop_column('park_factors', 'window_years')
    op.drop_table('park_dimensions')
    # ### end Alembic commands ###
