from abc import ABC, abstractmethod
import pandas as pd

class BasePredictionModel(ABC):
    @abstractmethod
    def train(self, X: pd.DataFrame, y: pd.Series) -> None: ...
    @abstractmethod
    def predict(self, X: pd.DataFrame) -> pd.Series: ...
    @abstractmethod
    def evaluate(self, X: pd.DataFrame, y: pd.Series) -> dict: ...
    @abstractmethod
    def save(self, path: str) -> None: ...
    @abstractmethod
    def load(self, path: str) -> None: ...
